### ISSUE TITLE
Vページに対するフィードバック

### ISSUE THREAD

**Issue by LambdaNote** [LambdaNote/polished-ruby-ja-feedbacks-beta1#161]

**Comment by spinute** [comment]
ライブリ→ライブラリ

**Comment by kakutani** [comment]
ご指摘ありがとうございます!

**Comment by kakutani** [comment]
たいへん長らくお待たせしてしまいって、恐縮です :bow:

いただいたフィードバックを12/13にリリースしたβ2版に反映させました! ありがとうございます。
https://www.lambdanote.com/collections/frontpage/products/products-polished-ruby-beta

β版をお持ちで、ユーザー登録済の方は、マイ本棚に新しいバージョン「β2」が追加されていますので「購入済みの電子書籍一覧」のページから新しいバージョンを生成・取得ください!

β2版へのフィードバックは別リポジトリになっております。
https://github.com/LambdaNote/polished-ruby-ja-feedbacks-beta2
こちらでも引き続きよろしくお願いいたします!
